# Generated by Django 3.0.7 on 2020-06-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maniac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
    ]
