# Generated by Django 3.0.7 on 2020-06-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniac', '0002_remove_customer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(default='', max_length=20)),
                ('venue_desc', models.CharField(default='', max_length=1000)),
                ('venue_cost', models.IntegerField(default=0)),
                ('venue_img', models.ImageField(default='', upload_to='maniac/images')),
            ],
        ),
    ]
